Add some scripts

diff --git a/ghq-init b/ghq-init
--- a/ghq-init
+++ b/ghq-init
@@ -14,6 +14,9 @@ if [ (count $argv) -lt 1 ]
   help_exit
 end
 
+set -e REPOSITORY_NAME
+set -e GITHUB_USER_NAME
+
 set argv $argv --
 
 set GITHUB_USER_NAME "tatsuroro"
@@ -22,8 +25,9 @@ set i 1
 while true
   switch $argv[$i]
     case -n
+      echo $argv[$i]
       set i (math $i + 1)
-      echo "Repository is" $argv[$i]
+      echo "Target Repository is" $argv[$i]
       set REPOSITORY_NAME $argv[$i]
     case -u
       set i (math $i + 1)
@@ -33,6 +37,11 @@ while true
       break
   end
   set i (math $i + 1)
+end
+
+if test -z '$REPOSITORY_NAME'
+  echo "Target repository name is required with -n arg"
+  exit 1
 end
 
 set TARGET_DIR "$HOME/src/github.com/$GITHUB_USER_NAME/$REPOSITORY_NAME"
